db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://localhost:5432/placingadssystem
db.user=postgres
db.password=1111

hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.show_sql=true
hibernate.hbm2ddl.auto=update

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.transaction=DEBUG

jwt.secret=very_long_and_secure_secret_key_minimum_256_bits
jwt.expiration=3600000

spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

ads.title.max-length=100
ads.description.max-length=1000
ads.promotion.daily-price=10.0

